### ISSUE TITLE
Uncought SyntaxError

### ISSUE THREAD

**Issue by anagrius** [halohalospecial/atom-elmjutsu#102]
```
Uncaught SyntaxError: Invalid regular expression: /?/: Nothing to repeat
    at new RegExp (<anonymous>)
    at regex (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:3299:9)
    at Function.func (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:12463:5)
    at A5 (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:110:11)
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:12490:13
    at Function.func (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:1343:12)
    at A2 (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:92:11)
    at Function.foldr [as func] (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:1058:9)
    at A3 (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:98:11)
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:1345:10
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:7:53
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:12496:12
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:47:12
    at /Users/thb/.atom/packages/elmjutsu/elm/indexer.js:17534:42
    at Function.func (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:17664:261)
    at A8 (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:128:11)
    at Function.func (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:19047:12)
    at A2 (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:92:11)
    at Object.callback (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:2438:18)
    at step (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:3073:39)
    at work (/Users/thb/.atom/packages/elmjutsu/elm/indexer.js:3131:15)
```

**Comment by halohalospecial** [comment]
Hi!  Do you have a way to reproduce this?  Also, what's your Atom version?
