### ISSUE TITLE
Whenever I say a file, a bunch of errors are thrown

### ISSUE THREAD

**Issue by cjduncana** [halohalospecial/atom-elmjutsu#104]
[Enter steps to reproduce:]

Save an Elm file

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.1.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/cjduncana/Development/three-words/tests/elm-stuff/packages/mgold-elm-random-pcg-fac8585/src/Random/Pcg.elm'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/Users/cjduncana/Development/three-words/tests/elm-stuff/packages/mgold-elm-random-pcg-fac8585/src/Random/Pcg.elm'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:360:18)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:176:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:218:5)
    at /packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:204:14)
    at addOrChange (/packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:210:7)
    at /packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:236:16)
    at filteredListener (/packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:58:7)
    at /packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:83:11
    at Array.forEach (native)
    at /packages/elmjutsu/node_modules/chokidar/lib/fsevents-handler.js:82:34)
    at emitThree (events.js:116:13)
    at FSEvents.emit (events.js:194:7)
    at /packages/elmjutsu/node_modules/fsevents/fsevents.js:47:11)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

### Commands

```
     -1:04.5.0 autocomplete-plus:confirm (input.hidden-input)
     -1:01.4.0 core:move-down (input.hidden-input)
     -1:01.0 autocomplete-plus:confirm (input.hidden-input)
 13x -0:55.2.0 core:undo (input.hidden-input)
     -0:44.9.0 core:move-down (input.hidden-input)
  3x -0:44.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:36.6.0 core:move-right (input.hidden-input)
     -0:27 core:move-down (input.hidden-input)
     -0:26.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:25.7.0 core:move-right (input.hidden-input)
  3x -0:22.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:16.3.0 core:save (input.hidden-input)
  2x -0:16.2.0 linter:toggle (atom-text-editor.editor.is-focused)
     -0:07.4.0 editor:newline (input.hidden-input)
     -0:06.9.0 core:save (input.hidden-input)
  2x -0:06.9.0 linter:toggle (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
atom-elm-test 0.7.0 
atom-material-ui 2.0.6 
atom-typescript 11.0.10 
autoclose-html 0.23.0 
autocomplete-haskell 1.0.1 
bezier-curve-editor 0.7.2 
blame 0.12.0 
busy-signal 1.4.3 
color-picker 2.2.5 
elm-format 3.0.0 
elm-snippets 0.1.0 
elmjutsu 7.1.5 
file-icons 2.1.13 
haskell-ghc-mod 2.1.3 
highlight-selected 0.13.1 
hyperclick 0.1.5 
ide-haskell 2.2.0 
ide-haskell-cabal 2.0.4 
ide-purescript 0.19.1 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-docker 1.1.8 
language-elm 1.5.0 
language-haskell 1.14.3 
language-nunjucks 4.1.0 
language-purescript 0.8.3 
language-r 0.4.2 
linter 2.2.0 
linter-elm-make 0.27.2 
linter-eslint 8.4.0 
linter-handlebars 2.5.0 
linter-jsonlint 1.3.0 
linter-lintr 1.1.4 
linter-markdown 5.2.0 
linter-mixed-indent 1.1.1 
linter-phplint 0.1.0 
linter-pycodestyle 2.1.3 
linter-pylint 2.1.0 
linter-shellcheck 1.4.6 
linter-stylelint 4.0.2 
linter-stylint 2.2.8 
linter-tslint 1.9.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
project-manager 3.3.5 
svg-preview 0.11.0 
symbols-tree-view 0.14.0 
sync-settings 0.8.3 
terminal-plus 0.14.5 
todo-show 2.1.0 
```

**Comment by halohalospecial** [comment]
@cjduncana, can you try v7.2.4?  Thanks!
