### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by AsaAyers** [halohalospecial/atom-elmjutsu#107]
I updated Atom and elmjutsu today. Before filing this issue I disabled all non-core packages.

[Enter steps to reproduce:]

1. Open an elm file.

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:656

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:376:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at /packages/linter-elm-make/node_modules/chokidar/lib/nodefs-handler.js:307:14)
    at LOOP (fs.js:1627:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
elmjutsu 7.2.2 
```

**Comment by n1k0** [comment]
Same here with:

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2

### Commands

```
     -0:54.7.0 core:move-right (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
elm-format 3.0.0 
elmjutsu 7.2.2 
intentions 1.1.5 
language-elm 1.5.0 
linter 2.2.0 
linter-elm-make 0.28.1 
linter-ui-default 1.6.10 
selection-highlight 0.1.6 
```

**Comment by AsaAyers** [comment]
I'm still on the same version of Atom and the same version of elmjutsu as Friday, but when I re-enabled it today I can't reproduce this error.

@n1k0 Are you sure you're getting the same error? You didn't include a stack trace and yours involves a command.

**Comment by n1k0** [comment]
This is the stack trace I got this morning just after starting Atom:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/home/niko/.atom/packages/elmjutsu/lib/indexing.js:15:21)
    at FSWatcher.<anonymous> (/home/niko/.atom/packages/elmjutsu/lib/core.js:376:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSWatcher.<anonymous> (/home/niko/.atom/packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/home/niko/.atom/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at FSWatcher.<anonymous> (/home/niko/.atom/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:307:14)
    at LOOP (fs.js:1627:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by n1k0** [comment]
Updated Atom to 1.24.0-beta3 and I'm still getting this error on startup, this time with no specific command involved:

**Atom**: 1.24.0-beta3 x64
**Electron**: 1.6.15
**OS**: "Fedora release
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2


### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:656

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:376:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:307:14)
    at LOOP (fs.js:1627:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
elm-format 3.0.0 
elmjutsu 7.2.2 
intentions 1.1.5 
language-elm 1.5.0 
linter 2.2.0 
linter-elm-make 0.28.1 
linter-ui-default 1.6.10 
selection-highlight 0.1.6 
```

**Comment by n1k0** [comment]
Still getting this error with latest stable Elmjutsu:

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2


### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:656

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:360:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at /packages/linter-elm-make/node_modules/chokidar/lib/nodefs-handler.js:302:16)
    at LOOP (fs.js:1627:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
elm-format 3.0.0 
elmjutsu 7.2.2 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
language-elm 1.5.0 
linter 2.2.0 
linter-elm-make 0.28.1 
linter-ui-default 1.7.0 
pretty-json 1.6.4 
```
