### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/Dev/ai-pros/user-web-service/assets/el...

### ISSUE THREAD

**Issue by addicteduser** [halohalospecial/atom-elmjutsu#111]
Error pops up on start-up of the Atom editor when an elm file is already opened.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 17.10
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/home/tintin/Dev/ai-pros/user-web-service/assets/elm/elm-stuff/generated-code/elm-community/elm-test/elm-stuff'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/home/tintin/Dev/ai-pros/user-web-service/assets/elm/elm-stuff/generated-code/elm-community/elm-test/elm-stuff'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:376:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:307:14)
    at fs.js:1666:23
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-elixir 0.2.3 
atom-elixir-formatter 1.0.2 
busy-signal 1.4.3 
color-picker 2.2.5 
docblockr 0.13.7 
elm-format 3.0.0 
elm-lens 0.3.0 
elm-test-runner 0.3.0 
elmjutsu 7.2.2 
file-icons 2.1.15 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
language-cassandra-cql 0.1.2 
language-docker 1.1.8 
language-elixir 0.22.0 
language-elm 1.5.0 
line-diff-details 1.9.0 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-elm-make 0.28.1 
linter-js-yaml 1.2.8 
linter-jshint 3.1.6 
linter-json-lint 0.1.2 
linter-markdown 5.2.0 
linter-ui-default 1.7.1 
markdown-preview-plus 2.4.16 
minimap 4.29.8 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.6.1 
```

**Comment by halohalospecial** [comment]
@addicteduser, can you try v7.2.4? Thanks!
