### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '~/xxxx/.#a.html'

### ISSUE THREAD

**Issue by nasyxx** [halohalospecial/atom-elmjutsu#112]
**In fact, this file is a temporary file, generating by emacs org-mode, probably only existed a few seconds. I think, maybe an ignore file list can solve it. **

Although it has little effect, I still hope it can be solved.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 7.2.2

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/Nasy/xxxx/.#a.html'

```
At fs.js:558

Error: ENOENT: no such file or directory, open '/Users/Nasy/xxxx/.#a.html'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:468:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at Object.sendFileContentsChanged (/packages/elmjutsu/lib/indexing.js:15:21)
    at /packages/elmjutsu/lib/core.js:376:18)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:198:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:240:5)
    at /packages/linter-elm-make/node_modules/chokidar/lib/nodefs-handler.js:307:14)
    at fs.js:1666:23
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -7:11.6.0 core:move-down (input.hidden-input)
     -7:10.6.0 find-and-replace:toggle (input.hidden-input)
     -7:05.7.0 editor:select-to-first-character-of-line (input.hidden-input)
     -6:52.7.0 core:cancel (button.btn.btn-next.disabled)
     -6:07.6.0 editor:select-to-first-character-of-line (input.hidden-input)
     -6:07.0 core:copy (input.hidden-input)
     -6:06.9.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -6:06.5.0 editor:newline (input.hidden-input)
     -6:06.2.0 core:paste (input.hidden-input)
     -5:51.9.0 core:copy (input.hidden-input)
     -5:48 core:paste (input.hidden-input)
     -5:42.3.0 editor:newline (input.hidden-input)
     -5:40.4.0 autocomplete-plus:confirm (input.hidden-input)
     -5:37.9.0 core:move-left (input.hidden-input)
     -5:37.7.0 core:move-down (input.hidden-input)
     -5:37.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.16 
atom-ide-ui 0.9.2 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
auto-update-packages 1.0.1 
autocomplete-html-entities 0.2.0 
autocomplete-modules 1.11.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
city-lights-ui 1.3.3 
compare-files 0.8.1 
ctags-status 1.3.7 
dash 1.7.1 
dash-ui 0.4.4 
elm-format 3.0.0 
elmjutsu 7.2.2 
emmet 2.4.3 
encourage 0.4.0 
fancy-bracket-matcher 2.1.0 
file-header 1.13.9 
file-icons 2.1.17 
flow-ide 1.10.0 
glowing-cursor 0.1.2 
grammar-token-limit 0.1.1 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-head-snippets 0.2.0 
html-to-elm 0.2.0 
hyperclick 0.0.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 0.8.1 
ide-typescript 0.7.5 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-elm 1.5.0 
line-count-status 0.0.3 
linter 2.2.0 
linter-elm-make 0.28.1 
linter-htmlhint 1.4.0 
linter-mypy 2.6.0 
linter-ui-default 1.7.1 
lisp-paredit 0.6.0 
livestyle-atom 0.2.10 
lunar-particle-ui 0.3.13 
MagicPython 1.0.12 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
multi-wrap-guide 1.1.5 
neon-cursor 1.6.0 
one-vibrancy 0.2.0 
organized 0.8.1 
parinfer 1.22.0 
pigments 0.40.2 
pure-syntax 0.3.0 
python-indent 1.1.4 
seti-icons 1.5.4 
seti-ui 1.10.0 
swackets 0.35.0 
symbol-gen 1.3.1 
sync-settings 0.8.5 
tree-view-copy-relative-path 1.2.0 
tree-view-git-status 1.4.0 
typewriter-sounds 3.0.1 
youtube-pane 2.0.0 
```

**Comment by kaskelotti** [comment]
Seems to be a duplicate to https://github.com/halohalospecial/atom-elmjutsu/issues/111

**Comment by nasyxx** [comment]
Sorry... I missed it.
