### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filePath' of null

### ISSUE THREAD

**Issue by absynce** [halohalospecial/atom-elmjutsu#117]
### Steps to reproduce:

1. Run "Elmjutsu: Add Import"
2. Error and empty dialog with "Loading..." display

![image](https://user-images.githubusercontent.com/289969/38880282-ed837716-422a-11e8-87a0-e76940e96da0.png)

**Atom**: 1.25.1 ia32
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 8.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'filePath' of null

```
At C:\Users\JSmith\.atom\packages\elmjutsu\lib\add-import.js:15

TypeError: Cannot read property 'filePath' of null
    at /packages/elmjutsu/lib/add-import.js:15:21
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /packages/elmjutsu/lib/indexer-worker.js:33:22)
    at /packages/elmjutsu/elm/indexer.js:2727:19)
    at A3 (/packages/elmjutsu/elm/indexer.js:98:11)
    at onMessage (/packages/elmjutsu/elm/indexer.js:2510:12)
    at Object.callback (/packages/elmjutsu/elm/indexer.js:2552:11)
    at step (/packages/elmjutsu/elm/indexer.js:3089:32)
    at work (/packages/elmjutsu/elm/indexer.js:3131:15)
```

### Commands

```
     -3:02.4.0 core:cancel (input.hidden-input)
     -2:49.5.0 intentions:highlight (input.hidden-input)
     -2:49.4.0 command-palette:toggle (input.hidden-input)
     -2:45.8.0 editor:delete-to-beginning-of-word (input.hidden-input)
     -2:44.7.0 core:confirm (input.hidden-input)
     -2:44.6.0 elmjutsu:install-package (input.hidden-input)
     -2:36.5.0 core:move-down (input.hidden-input)
  2x -2:35.3.0 core:confirm (input.hidden-input)
     -0:53.8.0 elmjutsu:add-import (input.hidden-input)
     -0:44.1.0 editor:consolidate-selections (input.hidden-input)
     -0:44.1.0 core:cancel (input.hidden-input)
  2x -0:42 elmjutsu:add-import (input.hidden-input)
     -0:37.4.0 core:move-down (input.hidden-input)
     -0:37 core:move-up (input.hidden-input)
     -0:36.4.0 elmjutsu:add-import (input.hidden-input)
     -0:25.3.0 intentions:highlight (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-beautify 0.32.2 
atom-ide-ui 0.9.4 
atom-typescript 12.3.8 
atom-yeoman 0.3.15 
atomic-chrome 0.3.3 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
css-declaration-sorter 1.2.0 
docblockr 0.13.7 
editorconfig 2.2.2 
elm-format 3.0.0 
elmjutsu 8.1.0 
ex-mode 0.18.0 
file-icons 2.1.18 
file-type-icons 1.3.4 
hidpi 0.14.0 
intentions 1.1.5 
jira-issue-search 1.0.3 
jsdoc-preview 1.2.1 
json-schema 0.1.15 
language-elm 1.5.0 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-elm-make 0.28.3 
linter-eslint 8.4.1 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
markdown-preview-plus 2.5.7 
markdown-table-editor 1.1.0 
markdown-writer 2.7.3 
node-debugger 1.10.1 
omnisharp-atom 0.31.2 
pigments 0.40.2 
prettier-atom 0.53.0 
seti-icons 1.5.4 
seti-ui 1.10.0 
solarized-seti-ui 0.8.6 
sort-lines 0.18.0 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
teletype 0.12.2 
template-generator 0.16.0 
terminal-panel 1.14.1 
tree-view-git-branch 0.1.2 
vim-mode-plus 1.32.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by absynce** [comment]
This went away when I updated `atom-ide-ui` from `0.9.4` to `0.10.1`.
