### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, scandir '~/AppData\Local\Microsoft\Windows\INetCa...

### ISSUE THREAD

**Issue by tohnk** [halohalospecial/atom-elmjutsu#122]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 8.2.0

### Stack Trace

Uncaught Error: EPERM: operation not permitted, scandir 'C:\Users\Amanda\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'

```
At fs.js:904

Error: EPERM: operation not permitted, scandir 'C:\Users\Amanda\AppData\Local\Microsoft\Windows\INetCache\Content.IE5'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (ELECTRON_ASAR.js:580:28)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:253:24)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/indexing.js:277:12
    at Array.forEach (<anonymous>)
    at Object.parseDirectoryFiles (/packages/elmjutsu/lib/indexing.js:276:21)
    at /packages/elmjutsu/lib/core.js:378:16
    at Array.forEach (<anonymous>)
    at Core.ensureWatchProject (/packages/elmjutsu/lib/core.js:376:23)
    at /packages/elmjutsu/lib/core.js:292:16
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at Workspace.didChangeActivePaneItemOnPaneContainer (~/AppData/Local/atom/app-1.28.1/resources/app/src/workspace.js:443:26)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem (~/AppData/Local/atom/app-1.28.1/resources/app/src/workspace-center.js:17:20)
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.28.1/resources/app/node_modules/event-kit/lib/emitter.js:27:20)
```

### Commands

```
     -3:46.9.0 core:select-all (input.hidden-input)
  3x -3:46.7.0 core:backspace (input.hidden-input)
     -3:14.8.0 core:select-all (input.hidden-input)
     -3:14.6.0 core:backspace (input.hidden-input)
  2x -1:50.5.0 core:confirm (input.hidden-input)
 27x -1:20.8.0 core:move-down (div.panels-item)
```

### Non-Core Packages

```
elmjutsu 8.2.0 
language-elm 1.5.0 
monokai 0.24.0 
```

**Comment by halohalospecial** [comment]
Hi! Are you perhaps missing an `elm-package.json` file?
