### ISSUE TITLE
Uncaught SyntaxError: Unexpected token e in JSON at position 0

### ISSUE THREAD

**Issue by dbj** [halohalospecial/atom-elmjutsu#124]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 8.3.2

### Stack Trace

Uncaught SyntaxError: Unexpected token e in JSON at position 0

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html:1

SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at /packages/elmjutsu/lib/elm-make.js:47:31)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

### Commands

```
     -0:37.1.0 core:save (input.hidden-input)
  2x -0:34.9.0 linter:toggle (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.33.0 
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
autoclose-html 0.23.0 
autocomplete-haskell 1.0.1 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
color-picker 2.3.0 
dash 1.7.1 
duotone-dark-earth-syntax 2.1.0 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-syntax 2.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
elm-format 3.2.0 
elmjutsu 8.3.2 
escape-utils 0.5.3 
git-log 0.4.1 
haskell-debug 0.3.6 
haskell-ghc-mod 2.2.4 
haskell-pointfree 0.2.0 
html-to-elm 0.2.0 
hyperclick 0.1.5 
ide-haskell 2.3.1 
ide-haskell-cabal 2.2.0 
ide-haskell-hasktags 0.0.15 
ide-haskell-hoogle 0.1.2 
ide-haskell-profiteurjs 0.1.0 
ide-haskell-repl 0.8.1 
intentions 1.1.5 
language-elm 1.5.0 
language-haskell 1.17.8 
language-haskell-scoped 0.1.1 
language-svg 0.9.2 
linter 2.2.0 
linter-csslint 2.0.1 
linter-elm-make 0.28.5 
linter-hlint 2.0.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.8 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
pigments 0.40.2 
seti-syntax 1.2.0 
seti-ui 1.11.0 
svg-preview 0.12.1 
svgo 3.1.0 
teletype 0.13.3 
todo-show 2.3.2 
```

**Comment by halohalospecial** [comment]
Hi @dbj, kindly check #123.
