### ISSUE TITLE
Uncaught Error: no parsers registered for: "]rack"

### ISSUE THREAD

**Issue by inspiredlabs** [halohalospecial/atom-elmjutsu#144]
Installed elmjutsu as normal & reopened atom using: `atom project-file.elm`

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.4
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 9.4.1

### Stack Trace

Uncaught Error: no parsers registered for: "]rack"

```
At /Users/scottphillips/.atom/packages/elmjutsu/node_modules/snapdragon/lib/parser.js:473

Error: no parsers registered for: "]rack"
    at parse (/packages/elmjutsu/node_modules/snapdragon/lib/parser.js:473:15)
    at Parser.parse (/packages/elmjutsu/node_modules/snapdragon/lib/parser.js:477:24)
    at Snapdragon.parse (/packages/elmjutsu/node_modules/snapdragon/index.js:122:28)
    at /packages/elmjutsu/node_modules/braces/lib/braces.js:40:45)
    at Braces.parse (/packages/elmjutsu/node_modules/braces/lib/braces.js:66:26)
    at Braces.expand (/packages/elmjutsu/node_modules/braces/lib/braces.js:87:18)
    at create (/packages/elmjutsu/node_modules/braces/index.js:142:15)
    at memoize (/packages/elmjutsu/node_modules/braces/index.js:298:13)
    at Function.braces.create (/packages/elmjutsu/node_modules/braces/index.js:165:10)
    at Function.braces.expand (/packages/elmjutsu/node_modules/braces/index.js:81:17)
    at getDirParts (/packages/elmjutsu/node_modules/chokidar/index.js:435:31)
    at /packages/elmjutsu/node_modules/chokidar/index.js:452:24)
    at /packages/elmjutsu/node_modules/readdirp/readdirp.js:220:72
    at Array.filter (<anonymous>)
    at /packages/elmjutsu/node_modules/readdirp/readdirp.js:220:12
    at /packages/elmjutsu/node_modules/readdirp/readdirp.js:193:38
    at /packages/elmjutsu/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Commands

```
```

### Non-Core Packages

```
ask-stack 2.2.0 
atom-jshint 2.0.0 
atom-material-ui 2.1.3 
busy-signal 1.4.3 
change-case 0.6.5 
elm-format 3.2.0 
elm-instant 2.0.0 
elmjutsu 9.4.1 
emmet 2.4.3 
formatter-gofmt 1.0.1 
go-plus 5.5.5 
html-to-elm 0.2.0 
hugofy 2.0.0 
intentions 1.1.5 
language-elm 1.5.0 
language-htaccess 0.1.1 
language-hugo 0.2.0 
lint 0.0.1 
linter 2.2.0 
linter-elm-make 0.28.5 
linter-json-lint 0.1.3 
linter-package-json-validator 2.0.0 
linter-ui-default 1.7.1 
material-palenight-syntax 1.5.7 
w3c-validation 0.4.0 
web-accessibility-checker 0.1.4 
wordpress-api 1.2.2 
wordpress-suite 1.0.4 
```

**Comment by halohalospecial** [comment]
@inspiredlabs, this might be related to https://github.com/paulmillr/chokidar/issues/699 ?
