### ISSUE TITLE
Uncaught Error: Trying to send an unexpected type of value through port `addImportSub`:Expecting...

### ISSUE THREAD

**Issue by aaahrens** [halohalospecial/atom-elmjutsu#146]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 9.9.0

### Stack Trace

Uncaught Error: Trying to send an unexpected type of value through port `addImportSub`:
Expecting a longer array. Need index 4 but there are only 4 entries but instead got: ["/Users/drunkengranite/projects/websites/cubicle-accounts-frontend/src/Toolbox/Input.elm","/Users/drunkengranite/projects/websites/cubicle-accounts-frontend","Html",null]

```
At /Users/drunkengranite/.atom/packages/elmjutsu/elm/indexer.js:2848

Error: Trying to send an unexpected type of value through port `addImportSub`:
Expecting a longer array. Need index 4 but there are only 4 entries but instead got: ["/Users/drunkengranite/projects/websites/cubicle-accounts-frontend/src/Toolbox/Input.elm","/Users/drunkengranite/projects/websites/cubicle-accounts-frontend","Html",null]
    at Object.send (/packages/elmjutsu/elm/indexer.js:2848:10)
    at /packages/elmjutsu/lib/indexer-worker.js:19:45)
    at Object.onDidInsertSuggestion (/packages/elmjutsu/lib/autocomplete-provider.js:569:17)
    at AutocompleteManager.confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:649746)
    at subscriptions.add.suggestionList.onDidConfirm.e (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:642768)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188425)
    at SuggestionList.confirm (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:495970)
    at SuggestionListElement.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1976045)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1186984)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1188425)
    at SuggestionList.confirmSelection (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:496031)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1227611)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1223745)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -0:53.5.0 intentions:highlight (input.hidden-input)
  2x -0:53.4.0 editor:move-to-end-of-word (input.hidden-input)
     -0:52.9.0 datatip:toggle (input.hidden-input)
     -0:50.9.0 core:move-left (input.hidden-input)
     -0:48.7.0 core:move-right (input.hidden-input)
     -0:47.5.0 core:save (input.hidden-input)
     -0:24.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.9.0 core:move-left (input.hidden-input)
     -0:20.2.0 autocomplete-plus:confirm (input.hidden-input)
     -0:17.7.0 core:move-right (input.hidden-input)
     -0:15.2.0 intentions:highlight (input.hidden-input)
     -0:15 datatip:toggle (input.hidden-input)
  2x -0:13 core:move-left (input.hidden-input)
     -0:11.7.0 core:move-right (input.hidden-input)
  2x -0:10 core:backspace (input.hidden-input)
     -0:07.6.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
autocomplete 0.47.0 
busy-signal 1.4.3 
elm-format 3.2.0 
elmjutsu 9.9.0 
file-icons 2.1.26 
go-plus 5.9.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
jenkins 0.3.5 
language-elm 1.5.0 
language-graphql 0.11.0 
language-hcl 0.4.0 
language-jenkinsfile 0.1.1 
linter 2.2.0 
linter-ui-default 1.7.1 
markdown-preview-plus 3.7.1 
Stylus 3.2.0 
```

**Comment by aaahrens** [comment]
Just been getting this a lot with the latest package, feel free to close

**Comment by halohalospecial** [comment]
Thanks a lot for reporting!
