### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by kafey** [halohalospecial/atom-elmjutsu#151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 9.10.1

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:323

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:514:9)
    at Object.executeElmInit (/packages/elmjutsu/lib/helper.js:824:31)
    at NotificationElement.onDidClick (/packages/elmjutsu/lib/helper.js:775:24)
    at HTMLAnchorElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:886144)
```

### Commands

```
     -8:20.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
busy-signal 1.4.3 
elmjutsu 9.10.1 
ide-python 1.1.0 
intentions 1.1.5 
kite 0.131.0 
language-elm 1.5.0 
python-indent 1.1.6 
```

**Comment by halohalospecial** [comment]
@kafey, can you check if your `Elm Path` (in the Settings view) is correct and executable?  Thanks!
