### ISSUE TITLE
Arguments to CompositeDisposable.add must have a .dispose() method

### ISSUE THREAD

**Issue by noklesta** [halohalospecial/atom-elmjutsu#22]
I just upgraded Atom to the latest version (1.11.0 on OS X El Capitan) and now elmjutsu cannot be activated. I get the following error message: 

`Arguments to CompositeDisposable.add must have a .dispose() method`

This seems to be caused by [this pull request](https://github.com/atom/event-kit/pull/28/commits) that was merged into atom/event-kit a few days ago, which causes code in `atom-elmjutsu/lib/symbol-finder.js` to trigger a TypeError.

**Comment by clojj** [comment]
+1 caused by Atom 1.11.0

**Comment by halohalospecial** [comment]
Hi all, thanks for the report!  I couldn't reproduce this on my computer (Lubuntu 16.04.1) :crying_cat_face: :   The new version (2.8.3) has a fix for a different issue that might also be related to this one.  Can anyone kindly confirm that this issue is also fixed?  Thanks!

**Comment by kristian-puccio** [comment]
I'm still getting this.
```
TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
  at assertDisposable (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:70:13)
  at CompositeDisposable.module.exports.CompositeDisposable.add (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:43:11)
  at GoToSymbol.SymbolFinder (/Users/kristian/.atom/packages/elmjutsu/lib/symbol-finder.js:23:24)
  at new GoToSymbol (/Users/kristian/.atom/packages/elmjutsu/lib/go-to-symbol.js:39:76)
  at Object.activate (/Users/kristian/.atom/packages/elmjutsu/lib/main.js:46:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:397:31
```

**Comment by gasperz** [comment]
I works ok with atom-elmjutsu 2.8.3 and Atom 1.11.1

**Comment by noklesta** [comment]
Yes, upgrading to 2.8.3 fixed the problem. Thanks a lot!

**Comment by noklesta** [comment]
@kristian-puccio do you still have problems? In that case I suppose I should reopen the issue.

**Comment by halohalospecial** [comment]
@kristian-puccio, can you check your elmjutsu and Atom versions?  If there are still problems, maybe elmjutsu was not upgraded properly.  You can try reinstalling it.  Thanks!

**Comment by kristian-puccio** [comment]
It seems to be working now with atom 1.11.1

Thanks!

**Comment by Positive07** [comment]
I had the same error, opening Atom triggers it

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Windows 10
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package, v2.8.2

### Stack Trace

Failed to activate the elmjutsu package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:70:13)
    at CompositeDisposable.module.exports.CompositeDisposable.add (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\composite-disposable.js:43:11)
    at GoToSymbol.SymbolFinder (C:/Users/Pablo/.atom/packages/elmjutsu/lib/symbol-finder.js:12:24)
    at new GoToSymbol (C:/Users/Pablo/.atom/packages/elmjutsu/lib/go-to-symbol.js:7:32)
    at Object.activate (C:/Users/Pablo/.atom/packages/elmjutsu/lib/main.js:18:23)
    at Package.module.exports.Package.activateNow (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:183:20)
    at C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:92:15)
    at C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\Pablo\AppData\Local\atom\app-1.11.1\resources\app.asar\src\atom-environment.js:779:28
```

### Commands

```
 11x -0:22.8.0 blur (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "nppBackup/",
      "nppBackup",
      "*.bak",
      ".bak"
    ],
    "telemetryConsent": "no",
    "themes": [
      "geneus-ui",
      "atom-dark-fusion-syntax"
    ]
  },
  "elmjutsu": {
    "cacheDirectory": "C:\\Users\\Pablo\\AppData\\Local\\Temp\\elmjutsu81721fSsK2PunWMr"
  }
}
```

### Installed Packages

```coffee
# User
atom-dark-fusion-syntax, v1.2.4 (inactive)
atom-oss-license, v1.0.0 (inactive)
autocomplete-glsl, v0.2.3 (inactive)
build, v0.65.0 (inactive)
build-love, v0.2.0 (inactive)
busy, v0.7.0 (inactive)
color-picker, v2.2.2 (inactive)
comment, v0.5.0 (inactive)
elmjutsu, v2.8.2 (inactive)
firewatch-syntax, v1.0.1 (inactive)
genesis-syntax, v1.0.7 (inactive)
geneus-ui, v0.1.2 (inactive)
gitignore-snippets, v0.2.5 (inactive)
hyperclick, v0.0.39 (inactive)
hyperclick-love, v0.4.0 (inactive)
keyboard-localization, v1.4.18 (inactive)
language-elm, v1.5.0 (inactive)
language-gitignore, v0.2.0 (inactive)
language-glsl, v2.0.1 (inactive)
language-lua, v0.9.11 (inactive)
linter, v1.11.18 (inactive)
linter-elm-make, v0.17.7 (inactive)
linter-luacheck, v1.1.6 (inactive)
love-atom, v2.3.3 (inactive)
obsidian-syntax, v0.2.0 (inactive)
seti-icons, v1.3.4 (inactive)
sync-settings, v0.7.2 (inactive)
text-manipulation, v0.6.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.59.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v1.0.0 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.68.2 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.209.3 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by kristian-puccio** [comment]
I wonder if this could be caused by opening via spotlight or via the
terminal?

**Comment by Positive07** [comment]
I'm sorry I just updated elmjutsu to 2.8.3 (the update didn't appear available in the status bar so I thought I was running on latest) and it seems to be fixed now, sorry for the trouble

**Comment by halohalospecial** [comment]
@Positive07 no worries! Good to know it's already working :+1:
