### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by dillonkearns** [halohalospecial/atom-elmjutsu#59]
# Steps to reproduce:
I ran Elmjutsu go to symbol from a shortcut key

**Atom**: 1.15.0-beta1 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 5.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of null

```
At /Users/dillon/Downloads/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:823

TypeError: Cannot read property 'slice' of null
    at TextBuffer.module.exports.TextBuffer.applyChange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:602:25)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:556:19)
    at /app.asar/node_modules/text-buffer/lib/text-buffer.js:537:26
    at TextBuffer.module.exports.TextBuffer.transact (/app.asar/node_modules/text-buffer/lib/text-buffer.js:818:18)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (/app.asar/node_modules/text-buffer/lib/text-buffer.js:535:21)
    at TextBuffer.module.exports.TextBuffer.setText (/app.asar/node_modules/text-buffer/lib/text-buffer.js:475:19)
    at TextEditor.module.exports.TextEditor.setText (/app.asar/src/text-editor.js:1087:26)
    at GoToSymbolView.setSymbols (/packages/elmjutsu/lib/go-to-symbol-view.js:18:38)
    at /packages/elmjutsu/lib/go-to-symbol.js:15:17)
    at /packages/elmjutsu/elm/indexer.js:3423:19)
    at A3 (/packages/elmjutsu/elm/indexer.js:98:11)
    at onMessage (/packages/elmjutsu/elm/indexer.js:3206:12)
    at Object.callback (/packages/elmjutsu/elm/indexer.js:3248:11)
    at step (/packages/elmjutsu/elm/indexer.js:2944:32)
    at work (/packages/elmjutsu/elm/indexer.js:2986:15)
```

### Commands

```
     -3:37.7.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -3:36.9.0 vim-mode-plus:delete-right (input.hidden-input)
     -3:36.5.0 dillon:normal-mode-and-save (input.hidden-input)
     -3:36.5.0 vim-mode-plus:reset-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -3:36.5.0 core:save (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  2x -3:36.3.0 linter:toggle (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  6x -3:34.6.0 blur (input.hidden-input)
  8x -0:08.0 vim-mode-plus:move-up (input.hidden-input)
     -0:06.1.0 elmjutsu:go-to-symbol (input.hidden-input)
  3x -0:06.1.0 blur (input.hidden-input)
     -0:05.0 editor:consolidate-selections (input.hidden-input)
     -0:05.0 core:cancel (input.hidden-input)
  2x -0:05.0 blur (input.hidden-input)
  3x -0:04.8.0 vim-mode-plus:move-down (input.hidden-input)
     -0:04.3.0 elmjutsu:go-to-symbol (input.hidden-input)
  2x -0:00.1.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-elixir 0.2.2 
atom-typescript 10.1.14 
autoclose-html 0.23.0 
autocomplete-haskell 0.7.2 
busy 0.7.0 
choose-pane 0.5.1 
color-picker 2.2.5 
cursor-history 0.9.1 
cyber-dojo 0.3.0 
dash 1.7.0 
elm-format 2.1.0 
elm-instant 2.0.0 
elm-snippets 0.1.0 
elmjutsu 5.0.3 
example-package 0.0.0 
expand-region 0.2.6 
git-diff-details 1.4.0 
haskell-ghc-mod 1.19.7 
hyperclick 0.0.40 
ide-haskell 1.9.3 
ide-haskell-repl 0.5.2 
jumpy 3.1.3 
language-diff 0.7.0 
language-elixir 0.17.0 
language-elm 1.5.0 
language-haskell 1.12.1 
linter 1.11.23 
linter-coffeelint 1.2.1 
linter-elixir-credo 1.1.0 
linter-elm-make 0.22.4 
minitest-snippets 0.2.0 
narrow 0.29.0 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.1 
package-sync 1.1.0 
pigments 0.39.0 
quick-highlight 0.8.1 
ruby-block 0.3.6 
ruby-test 1.0.0 
smalls 0.3.0 
toggle-markdown-task 0.6.0 
vim-mode-plus 0.82.3 
vim-mode-plus-duplicate 0.2.0 
vim-mode-plus-exchange 0.2.1 
vim-mode-plus-move-selected-text 0.8.1 
vim-mode-plus-move-to-symbols 0.2.0 
vim-mode-plus-replace-with-execution 0.1.3 
```

**Comment by halohalospecial** [comment]
Hi @dillonkearns, this is a regression bug.  It's already fixed in my local repo.  Will it include it in the next release.  Thanks!

**Comment by dillonkearns** [comment]
Wonderful, thanks, and thank you for this awesome project @halohalospecial!
