### ISSUE TITLE
Uncaught Error: watch ~/workspace/HUMIO/humio/ui/node_modules/node-sass/test/fixtures/source-map ...

### ISSUE THREAD

**Issue by xorsnn** [halohalospecial/atom-elmjutsu#68]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 5.4.0

### Stack Trace

Uncaught Error: watch /home/xors/workspace/HUMIO/humio/ui/node_modules/node-sass/test/fixtures/source-map ENOSPC

```
At events.js:160

Error: watch /home/xors/workspace/HUMIO/humio/ui/node_modules/node-sass/test/fixtures/source-map ENOSPC
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-typescript 10.1.15 
autocomplete-clang 0.10.0 
autocomplete-cmake 0.3.1 
autocomplete-glsl 0.2.3 
busy-signal 1.3.0 
clang-format 1.28.0 
elm-format 2.1.0 
elm-sm 0.2.3 
elmjutsu 5.4.0 
intentions 1.1.2 
language-cmake 0.3.0 
language-docker 1.1.7 
language-elm 1.5.0 
language-glsl 2.0.1 
language-pug 0.0.21 
linter 2.1.0 
linter-clang 3.4.9 
linter-coffeelint 1.2.1 
linter-elm-make 0.23.2 
linter-glsl 2.1.2 
linter-ui-default 1.2.1 
react 0.16.2 
sort-lines 0.14.0 
vim-mode 0.66.0 
```

**Comment by halohalospecial** [comment]
Hi @xorsnn, when did you encounter this error?

Can you also check if you still have available disk space?  You can check this out: http://stackoverflow.com/questions/22475849/node-js-error-enospc
