### ISSUE TITLE
Uncaught ReferenceError: indexer is not defined

### ISSUE THREAD

**Issue by xorsnn** [halohalospecial/atom-elmjutsu#69]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 5.4.0

### Stack Trace

Uncaught ReferenceError: indexer is not defined

```
At /home/xors/.atom/packages/elmjutsu/lib/indexing.js:21

ReferenceError: indexer is not defined
    at Object.sendFileContentsRemoved (/packages/elmjutsu/lib/indexing.js:21:5)
    at /packages/elmjutsu/lib/core.js:258:18)
    at emitOne (events.js:96:13)
    at FSWatcher.emit (events.js:188:7)
    at /packages/elmjutsu/node_modules/chokidar/index.js:176:15)
    at FSWatcher._emit (/packages/elmjutsu/node_modules/chokidar/index.js:218:5)
    at FSWatcher._remove (/packages/elmjutsu/node_modules/chokidar/index.js:534:50)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:261:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -0:39.5.0 tabs:close-tabs-to-right (li.texteditor.tab.sortable.right-clicked)
  3x -0:39.5.0 blur (input.hidden-input)
     -0:36.3.0 tabs:close-tabs-to-right (li.texteditor.tab.sortable.right-clicked)
 10x -0:29.3.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-typescript 10.1.15 
autocomplete-clang 0.10.0 
autocomplete-cmake 0.3.1 
autocomplete-glsl 0.2.3 
busy-signal 1.3.0 
clang-format 1.28.0 
elm-format 2.1.0 
elm-sm 0.2.3 
elmjutsu 5.4.0 
intentions 1.1.2 
language-cmake 0.3.0 
language-docker 1.1.7 
language-elm 1.5.0 
language-glsl 2.0.1 
language-pug 0.0.21 
linter 2.1.0 
linter-clang 3.4.9 
linter-coffeelint 1.2.1 
linter-elm-make 0.23.2 
linter-glsl 2.1.2 
linter-ui-default 1.2.1 
react 0.16.2 
sort-lines 0.14.0 
vim-mode 0.66.0 
```

**Comment by pruett** [comment]
Not sure if this is helpful, but I seem to be getting this error when running commands in my terminal within the `elm repl`.

**Comment by halohalospecial** [comment]
Thanks @xorsnn and @pruett!
