### ISSUE TITLE
Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by Fenntasy** [halohalospecial/atom-elmjutsu#7]
Each time there is an update or when I launch Atom, I get this error `Cannot find module 'underscore-plus'`. Here is the stack trace given by Atom. Thanks in advance :)

**Atom Version**: 1.9.9
**System**: Mac OS X 10.11.6
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package, v1.1.0

### Stack Trace

Failed to activate the elmjutsu package

```
At Cannot find module 'underscore-plus'

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fenn/.atom/packages/elmjutsu/lib/helper.js:6:11)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/fenn/.atom/packages/elmjutsu/lib/main.js:7:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-vim"
    ],
    "themes": [
      "seti-ui",
      "earthsung-by-jackson-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.4 (inactive)
advanced-open-file, v0.16.3 (inactive)
api-docs, v0.0.6 (inactive)
atom-beautify, v0.29.10 (inactive)
atom-handlebars, v1.3.0 (inactive)
atom-monokai, v0.10.4 (inactive)
blame, v0.10.0 (inactive)
blocky, v0.8.0 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
earthsung-by-jackson-syntax, v0.3.0 (inactive)
elm-format, v2.0.1 (inactive)
elm-fu, v0.1.0 (inactive)
elmjutsu, v1.1.0 (inactive)
expand-selection-to-quotes, v0.9.0 (inactive)
goto, v1.7.1 (inactive)
highlight-nbsp, v0.1.1 (inactive)
highlight-selected, v0.11.2 (inactive)
hyperclick, v0.0.37 (inactive)
improved-chester-atom-syntax, v0.2.0 (inactive)
js-hyperclick, v1.4.2 (inactive)
language-elm, v1.5.0 (inactive)
language-emblem, v0.2.0 (inactive)
linter, v1.11.16 (inactive)
linter-coffeelint, v1.1.2 (inactive)
linter-eslint, v7.2.4 (inactive)
minimap, v4.24.7 (inactive)
monokai-seti, v0.7.0 (inactive)
natural-autoflow, v0.2.3 (inactive)
rails-i18n-autocomplete, v0.4.0 (inactive)
ruby-slim, v0.2.0 (inactive)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
standardjs-snippets, v2.4.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (inactive)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by halohalospecial** [comment]
Could you still use the `elmjutsu` package after getting the error?  I also encountered issues like this before with other packages, but it's a bit tricky to solve.

Maybe you can try the following:

1. Uninstall the `elm-fu` package (that's the old name of the `elmjutsu` package).

1. Uninstall `elmjutsu`.

1. Exit `Atom`.

1. Go to the `~/.atom/packages` directory and delete the `elm-fu` and `elmjutsu` directories.

1. Start `Atom`.

1. Reinstall `elmjutsu`.

1. Exit `Atom`.

1. Restart `Atom`.

**Comment by Fenntasy** [comment]
Sorry, I should have been more precise. Yes I still could use elmjutsu anyway.

I didn't know they were the same packages but thanks, your solution did the trick :)

Thanks for your work by the way ❤️

**Comment by halohalospecial** [comment]
Yeah, sorry I could not think of a suitable name for the package before.  I just wanted it to be as general (or vague) as possible so that I can just add in any Elm-related feature :smiley_cat: 

> There are only two hard things in Computer Science: cache invalidation and naming things.
-- Phil Karlton
