### ISSUE TITLE
Uncaught Error: watch ~/workspace/humio/ui/src/elm/Utils/Dom.elm ENOSPC

### ISSUE THREAD

**Issue by xorsnn** [halohalospecial/atom-elmjutsu#90]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.3
**Thrown From**: [elmjutsu](https://github.com/halohalospecial/atom-elmjutsu) package 5.6.3

### Stack Trace

Uncaught Error: watch /home/xors/workspace/humio/ui/src/elm/Utils/Dom.elm ENOSPC

```
At events.js:160

Error: watch /home/xors/workspace/humio/ui/src/elm/Utils/Dom.elm ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at /packages/elmjutsu/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -0:12.2.0 tree-view:add-file (span.name.icon.icon-file-directory)
  6x -0:08.9.0 core:backspace (input.hidden-input)
     -0:06.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
busy-signal 1.4.3 
clang-format 1.29.0 
elm-format 2.2.0 
elmjutsu 5.6.3 
intentions 1.1.5 
language-cmake 0.3.0 
language-elm 1.5.0 
language-gn 0.2.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-elm-make 0.23.8 
linter-ui-default 1.6.7 
vim-mode-plus 1.0.0 
```

**Comment by halohalospecial** [comment]
Hi!  Maybe there are too many watched files?  You can check https://stackoverflow.com/questions/22475849/node-js-error-enospc for possible solutions.

**Comment by halohalospecial** [comment]
Hi @xorsnn, this worked for me:

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`
